# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# For Travis. But this is needed in osx.
# setup_travis

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(
    task: "assembleRelease"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "c9e466da83a5a3f3695fcc0b1f52feb2291cf522",
    build_secret: "fce3441152116bb6ddff6ffd3e6e2d9f0d87732c47788a90d728cc83ff3f125e"
  )

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end